### ISSUE TITLE
Loading lancer.json fails on bytes vs. str

### ISSUE THREAD

**Issue by twm** [glyph/lancer#5]
After a failed attempt to run lancer, I just get this when I re-run it:

```
$ lancer jame.twm.space/certs
Traceback (most recent call last):
  File "/home/twm/.local/bin/lancer", line 11, in <module>
    sys.exit(script())
  File "/home/twm/.local/venvs/lancer/lib/python3.5/site-packages/lancer/_impl.py", line 108, in script
    react(main)
  File "/home/twm/.local/venvs/lancer/lib/python3.5/site-packages/twisted/internet/task.py", line 908, in react
    finished = main(_reactor, *argv)
  File "/home/twm/.local/venvs/lancer/lib/python3.5/site-packages/lancer/_impl.py", line 53, in main
    cfg = json.loads(myconfig.getContent())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Maybe Python 3 is why it failed the first time?

**Comment by twm** [comment]
I reinstalled under Python 2.7 and now I'm just flummoxed:

```
$ lancer jame.twm.space/certs
Traceback (most recent call last):
  File "/home/twm/.local/bin/lancer", line 7, in <module>
    from lancer._impl import script
  File "/home/twm/.local/venvs/lancer/local/lib/python2.7/site-packages/lancer/_impl.py", line 4, in <module>
    from secretly import secretly
  File "/home/twm/.local/venvs/lancer/local/lib/python2.7/site-packages/secretly/__init__.py", line 4, in <module>
    from ._impl import secretly
  File "/home/twm/.local/venvs/lancer/local/lib/python2.7/site-packages/secretly/_impl.py", line 243
    return pinentry
SyntaxError: 'return' with argument inside generator
```

So secretly _only_ supports Python 3?

**Comment by glyph** [comment]
Yeah I think probably secretly doesn't support python 2 any more.  Did you want to fix this as well?

FYI, this should have worked on py3.6; bytes are now acceptable.  But since pypy doesn't have a 3.6 yet I am grateful for the fix :)

**Comment by twm** [comment]
Ah cool, it was really irritating to have to make that extra copy to decode JSON. Great to see the maximal incompatibility of the early Python 3 days gradually walked back.

I think it's fine to only support Python 3. 3.5+ is a good target, as 3.5 is native in Ubuntu 16.04. I wouldn't expend any effort on 2.7 for a CLI tool like this.
